repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        stages: [pre-commit]
        language: system
        entry: bash -c 'poetry run ruff format . --preview && git add .'
        pass_filenames: false
      - id: stubgen
        name: stubgen
        stages: [pre-commit]
        language: system
        entry: bash -c 'poetry run stubgen -p horsetalk -o out && git add .'
        pass_filenames: false
      - id: sphinx-build
        name: build sphinx docs
        entry: bash -c 'poetry run sphinx-build -b html docs/source docs/build'
        language: system
        files: '\.py$|docs/source/.*\.rst$'
