name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up locale
        run: |
          sudo apt-get update
          sudo apt-get install -y locales
          sudo locale-gen en_GB
          sudo update-locale LANG=en_GB
          export LANG=en_GB
          export LC_ALL=en_GB

      - name: Set up python version ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install maturin # Temporary workaround because otherwise installation of sphinx fails
        run: pip install maturin

      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run static type checker
        run: poetry run mypy horsetalk

      - name: Run tests
        run: poetry run pytest --cov-fail-under=100

      - name: Run linter
        run: poetry run ruff check . --exclude out --preview

      
