name: version-forget-me-not

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

permissions:
  contents: read
  statuses: write

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.actor != 'dependabot[bot]'
    steps:
      - uses: simplybusiness/version-forget-me-not@v2.4.3
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_FILE_PATH: "pyproject.toml"
